# Generated by Django 6.1.1 on 2026-09-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_poster_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Если пусто — сгенерируется автоматически. Оптимум 120–160 символов.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='hall',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если пусто — сгенерируется автоматически. Оптимум 50–65 символов.', max_length=70, verbose_name='Meta Title'),
        ),
    ]
