# Generated by Django 6.1.1 on 2026-09-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_hall_meta_description_hall_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Заполняется автоматически при каждом сохранении.', verbose_name='Обновлено'),
        ),
    ]
