# Generated by Django 6.1.1 on 2026-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_fill_hall_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполнится автоматически из названия. Можно переопределить.', max_length=120, unique=True, verbose_name='URL'),
        ),
    ]
