# Generated by Django 6.1.1 on 2026-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_alter_hall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполнится автоматически из названия.', max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
    ]
