# Generated by Django 6.1.1 on 2026-09-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_alter_hall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.CharField(default='img/hall-depo.webp', max_length=200, verbose_name='Картинка (путь в static)'),
        ),
    ]
